### PR TITLE
Mvvm closures

### PR DESCRIPTION
**Pull request by amadeu01**
Added MVVM with closures

### CODE REVIEW

**Comment by amadeu01** [comment]
@tailec I'm gonna change this PR.

I'm gonna remove the first commit. Moreover, I saw something that I did wrong with the closures.

**Comment by tailec** [comment]
@amadeu01 💯 
What about removing `ReposViewModelOutput` and add closures as variables in view model? Like, here https://github.com/tailec/ios-architecture/issues/4
Also you could leave the comment or smth that outputs can be defines as protocol etc etc.

Let's make it super simple so people that are new to iOS dev don't get overwhelmed

**Comment by amadeu01** [comment]
@tailec sorry the delay, I'm gonna fix it. Then, update the PR

**Comment by amadeu01** [comment]
@tailec check it now. Look if it is fine for you!

**Comment by tailec** [comment]
Great!

**Pull request merged**
